### ISSUE TITLE
Small speedup, maybe.

### ISSUE THREAD

**Issue by yuriy-chumak** [aoh/owl-lisp#20]
Hello,

Maybe this will be interesting for you:
I have made some tests and found that in case of splitting the "25" virtual machine command (that in fact contains two commands - 25 and 89) into completely separated ones, the whole runtime speeds up approx. 5%.

This command(s) use a lot (~18% of common application time) and cpu's branch predictor does not work fine for most cases.

**Comment by aoh** [comment]
Yes, that would likely make sense. Arity checking is combined with variable arity checking to save opcodes, but it likely causes unnecessary trouble for the branch predictor. You can already ease the task of it by swapping NEXT and NEXT_ALT to copy the opcode dispatch table to each instruction (a cool trick pioneered by some Forth systems), instead of jumping to one dispatch table from each opcode, which seems to cut down opcode dispatch time by up to 20% in some benchmarks. Splitting 25 as you suggested would further help both in compiled and interpreted code whether NEXT_ALT is used or not.

I'll try this out tomorrow and see what happens.

**Comment by aoh** [comment]
The bench/ benchmarks showed a 0-9% increase in speed after splitting op 25, with an average of about 4% improvement. Looks good. Thanks for the suggestion!

**Comment by yuriy-chumak** [comment]
You're welcome.
